[build]
base    = "www"
publish = "public"
command = "zola build"

[build.environment]
ZOLA_VERSION = "0.19.1"
PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD = "1"

[context.deploy-preview]
command = "zola build --base-url $DEPLOY_PRIME_URL"
